[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_TITLE = "<span class='hvr-grow'>hey,</span>"
#LANDING_DESCRIPTION = "<div style='margin-bottom: 1rem; margin-top: -3rem;'> developed some <div style='font-size: 2rem; display: inline-block' class='animate__animated animate__pulse animate__infinite '>🔨</div> ideas.</div>"
LANDING_DESCRIPTION = "i'm thinkin' here!"
LANDING_BUTTON = "Explore 🌎"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "00 home"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/rosarioscalise/simulators"
# (Optional) Site title in navbar
SITE_TITLE = "rms dev ✨"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = ""
# (REQUIRED) Netlify site URL
SITE_URL = "https://rms.dev"
# (Optional) Site Timezone
TIMEZONE = "Los Angeles"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = ""
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = ""
